name: Release Package
on:
  workflow_dispatch:
  
jobs:
  Release_Package:
    env:
        SONAR_KEY: ${{ secrets.SONAR_KEY }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    runs-on: windows-latest
    uses: LoafThePenguin/actions/.github/workflows/CheckAndPushPackage.yml@main
    with: 
      PROJECT: LoafThePenguin.Helpers
      SONAR_KEY: ${{ env.SONAR_KEY }}
      SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
